#ABNF 1.0 UTF-8;
language zh-CN; 
mode voice;

root $main;
$main = $place1 $place2 $place3
|$people 在 $address
|$words;

$place1 = 向|往;
$place2 = 前|后|左|右;
$place3 = 走|跑|移动|行走;
$people = 李馨琪|鹿晓雷|张集栋|周家莉|叶震珂|熊泽萌;
$address = 佳晨实业|蜀南庭苑|高兰路|复联二;
$words = 洪荒之力|何弃疗|吃瓜群众|铲屎官|千禧一代|悔脱欧;