#BNF+IAT 1.0 UTF-8;
!grammar commands;
!slot <words>;
/******************************************** 一些公用的词 ****************************************/
!slot <ba>;
!slot <giveMe>;
!slot <iWant>;
!slot <turnOn>;
!slot <turnOff>;
!slot <scan>;
!slot <listen>;
!slot <look>;
!slot <UI>;
/********************************************* 唱歌 ***********************************************/
!slot <sing>;
!slot <oneSong>;
!slot <music>;
/********************************************* 跳舞 ***********************************************/
!slot <jump>;
!slot <oneDance>;
!slot <dance>;
!slot <danceStart>;
!slot <danceEnd>;
/********************************************* 拍照 ***********************************************/
!slot <take>;
!slot <onePicture>;
!slot <picture>;
!slot <camera>;
/********************************************* 打电话 *********************************************/
!slot <contact>;
!slot <call>;
!slot <oneCall>;
!slot <phone>;
/**************************************** 空调、电视、投影 ****************************************/
!slot <household>;
/********************************************** 关机 **********************************************/
!slot <shutdown>;
/********************************************* 查看照片 *******************************************/
!slot <whatPhoto>;
!slot <photos>;
/********************************************* 多媒体视频 *****************************************/
!slot <medias>;
/********************************************* 多媒体音频 *****************************************/
!slot <arts>;
/********************************************* 打开游戏界面****************************************/
!slot <whatGame>;
!slot <game>;
/********************************************* 打开一些界面****************************************/
!slot <qrCodeScan>;
!slot <qrCode>;
!slot <settings>;
!slot <scanSettings>;
!slot <tools>;
!slot <launcher>;
/********************************************* 音量调节 *******************************************/
!slot <volume>;
!slot <pole>;
!slot <voiceUp>;
!slot <voiceDown>;
!slot <whatVolume>;
!slot <speak>;
/**************************************** 自定义可以更新的变量 ************************************/
!slot <updateWords>;
!start <commandStart>;

<commandStart>:
<words>|
/********************************************* 唱歌 ***********************************************/
[<iWant>]<listen>[<oneSong>]<music>|
[<giveMe>]<sing>[<oneSong>]<music>|
<sing>[<oneSong>]<music><giveMe><listen>|
/********************************************* 跳舞 ***********************************************/
<danceStart><jump><dance>|
[<giveMe>]<jump>[<oneDance>]<dance>|
<jump>[<oneDance>]<dance><giveMe><look>|
<jump>[<oneDance>]<dance><danceEnd>|
/********************************************* 拍照 ***********************************************/
[<giveMe>]<take>[<onePicture>]<picture>|
[<iWant>]<take>[<onePicture>]<picture>|
[<giveMe>]<turnOn><camera>|
/********************************************* 打电话 *********************************************/
[<iWant>]给<contact><call>[<oneCall>]<phone>|
[<iWant>]<call>[<oneCall>]<phone>给<contact>|
[<iWant>]<call>[<oneCall>]<phone>|
<ba><phone><turnOn>|
/**************************************** 空调、电视、投影 ****************************************/
<ba><household><turnOn>|<turnOn><household>|
<ba><household><turnOff>|<turnOff><household>|
/********************************************** 关机 **********************************************/
[<iWant>]<shutdown>|
[<giveMe>]<shutdown>|
/********************************************* 查看照片 *******************************************/
[<giveMe>]<turnOn>[<whatPhoto>]<photos>|
[<iWant>]<turnOn>[<whatPhoto>]<photos>|
[<iWant>]<scan>[<whatPhoto>]<photos>|
/********************************************* 多媒体视频 *****************************************/
/*[<giveMe>]<turnOn><medias>[<UI>]|*/
/*[<iWant>]<look><medias>[节目]|*/
[<iWant>]<look><medias>|
/********************************************* 多媒体音频 *****************************************/
/*[<giveMe>]<turnOn>(<arts>|音乐!id(5))[<UI>]|*/
/*[<iWant>]<turnOn>(<arts>|音乐!id(5))[<UI>]|*/
/*[<giveMe>]<sing>[<oneSong>]<arts>|*/
/*[<iWant>]<listen><arts>|*/
/********************************************* 打开游戏界面****************************************/
[<giveMe>]<turnOn>[<whatGame>]<game>[<UI>]|
[<iWant>]<turnOn>[<whatGame>]<game>[<UI>]|
<iWant>玩[<whatGame>]<game>|
/********************************************* 打开一些设置****************************************/
<qrCodeScan><qrCode>|
<turnOn><settings>[<UI>]|
<turnOn><scanSettings>[<UI>]|
查看<scanSettings>|
/********************************************* 打开工具界面****************************************/
[<iWant>]<turnOn><tools>|
/********************************************* 打开LAUNCHER ***************************************/
[<iWant>]<turnOn><launcher>|
/********************************************* 音量调节 *******************************************/
<voiceUp>[<whatVolume>]<volume>|
<voiceDown>[<whatVolume>]<volume>|
[<ba>]<volume>调到<pole>|
[<ba>]<volume><voiceUp>[<whatVolume>]|
[<ba>]<volume><voiceDown>[<whatVolume>]|
[<speak>]<volume><voiceUp>[<whatVolume>]|
[<speak>]<volume><voiceDown>[<whatVolume>]|
[<speak>](大|小)<volume><whatVolume>|
[<speak>](大|小)<whatVolume><volume>|
/**************************************** 自定义可以更新的变量语句 ********************************/
<updateWords>;


<words>:过来;
/******************************************** 一些公用的词 ****************************************/
<ba>:把;
<giveMe>:给我|帮我;
<iWant>:我想|我要|我想要;
<turnOn>:打开|开启|启动;
<turnOff>:关闭|关掉|关了|关上;
<scan>:看|查看|提取|显示|浏览|进入;
<listen>:听;
<look>:看;
<UI>:界面;
/******************************************** 唱歌 ************************************************/
<sing>:唱|播|放|播放;
<oneSong>:首|一首|支|一支;
<music>:戏曲|舞曲|儿歌|歌|曲|歌曲|音乐;
/***********************************<music>:歌|曲|歌曲|音乐;***************************************/
/********************************************* 跳舞 ***********************************************/
<danceStart>:请|你|请你|请你跳|快|跳|跳舞;
<jump>:跳|来|秀;
<oneDance>:个|一个|支|一支|段|一段|下|一下;
<dance>:舞;
<danceEnd>:来看|好不好|怎么样|咋样;
/********************************************* 拍照 ***********************************************/
<take>:拍;
<onePicture>:个|一个|张|一张;
<picture>:照|照片;
<camera>:相机|照相机;
/********************************************* 打电话 *********************************************/
<contact>:10086;
<call>:，打|，拨|，拨打;
<oneCall>:个|一个|通|一通;
<phone>:电话;
/**************************************** 空调、电视、投影 ****************************************/
<household>:空调!id(1)|电视!id(2)|投影!id(3);
/********************************************* 关机 ***********************************************/
<shutdown>:关机|你关机;
/********************************************* 查看照片 *******************************************/
<whatPhoto>:拍的|照的|我的;
<photos>:相册|照片|相片;
/********************************************* 多媒体视频 *****************************************/
/*********<medias>:电视剧!id(1)|电影!id(2)|动漫!id(3)|综艺!id(4)|体育!id(5)|直播!id(6);************/
<medias>:视频!id(7);
/********************************************* 多媒体音频 *****************************************/
<arts>:戏曲!id(1)|儿歌!id(2)|文学!id(3)|电台!id(4);
/********************************************* 打开游戏界面****************************************/
<whatGame>:体感|手柄;
<game>:游戏;
/********************************************* 打开一些设置****************************************/
<qrCodeScan>:打开!id(1)|显示!id(1)|扫一扫!id(1)|查看!id(1)|绑定!id(1)|下载!id(2);
<qrCode>:二维码;
<settings>:设置!id(1)|机器人设置!id(1)|网络设置!id(2)|无线网络!id(2)|WIFI!id(3)|歪发!id(3)|
蓝牙!id(4)|关于!id(5)|关于机器人!id(5)|飞行模式!id(6)|网络热点!id(7)|显示!id(8)|
提示音!id(9)|音量!id(9)|位置信息!id(10)|语言!id(11)|日期!id(12)|时间!id(12)|日期和时间!id(12)|
重置!id(13)|出厂!id(13)|出厂设置!id(13);
<scanSettings>:存储状况!id(14)|存储信息!id(14)|电池电量!id(15)|应用状况!id(16)|应用列表!id(16)|应用信息!id(16);
/********************************************* 打开工具界面****************************************/
<tools>:下载!id(1)|我的下载!id(1)|我的信息!id(2)|我的短信!id(2)|信息!id(2)|短信!id(2)|录音机!id(3)|
文档管理!id(4)|日历!id(5)|时钟!id(6)|浏览器!id(7)|通讯录!id(8);
/********************************************* 打开LAUNCHER ***************************************/
<launcher>:应用!id(1)|我的应用!id(1)|影视!id(2)|文艺馆!id(3)|工具!id(4)|投影设置!id(5)|投影设置界面!id(5)|
学习!id(6)|遥控器!id(7);
/********************************************* 音量调节 *******************************************/
<volume>:声|声音|音量;
<pole>:最高|最低|最大|最小;
<voiceUp>:增加|增大|调大|调高|加大|大|响;
<voiceDown>:减少|减小|减|调小|调低|降低|降|低|小;
<whatVolume>:点|一点|些|一些;
<speak>:说话|讲话;
/**************************************** 自定义可以更新的变量语句 ********************************/
<updateWords>:
今天天气怎么样呀!id(1)|
你会做什么呀!id(2)|
你在这里做什么!id(3)|
你不用上学吗!id(4)|
你不是机器人么!id(5)|
你是谁!id(6)|
你是男孩还是女孩!id(7)|你是男的还是女的!id(7)|
为什么会先看到闪电，再听到打雷!id(8)|
你多大了!id(9)|你几岁了!id(9)|你今年多大了!id(9)|
为什么星星会一闪一闪的!id(10)|
你要吃饭吗!id(11)|你吃饭了吗!id(11)|你需要吃饭吗!id(11)|
我可以和你玩吗!id(12)|我想和你玩!id(12)|
你的爸爸妈妈呢!id(13)|
为什么你这么可爱!id(14)|
你的朋友呢!id(15)|你有朋友吗!id(15)|
再见!id(16)|拜拜!id(16)|我们走咯!id(16)|
我喜欢隔壁家的小花!id(17)|
你漂亮还是我漂亮!id(18)|
一加一等于多少!id(19)|
二加二等于多少!id(20)|
我生病了怎么办!id(21)|
我今天不舒服!id(22)|
成语亡羊补牢什么意思!id(23)|
你知道机器人和人的区别吗!id(24)|
你有多高!id(25)|
给我背一下九九乘法口诀表!id(26)|
为什么打雷的时候会闪电!id(27)|
讲一个故事!id(28)|给我讲一个故事!id(28)|
为什么肚子饿了会咕咕叫!id(29)|
你喜欢看动画片吗!id(30)|
你会不开心吗!id(31)|
讲一个笑话!id(32)|给我讲一个笑话!id(32)|
背首诗!id(33)|背首唐诗!id(33)|
守株待兔是什么意思!id(34)|
猫的英文怎么说!id(35)|
狗的英文怎么说!id(36)|
小鸟的英文怎么说!id(37)|
猴子的英文怎么说!id(38)|
长颈鹿的英文怎么说!id(39)|
天鹅的英文怎么说!id(40)|
大象的英文怎么说!id(41)|
乌龟的英文怎么说!id(42)|
眼睛的英文怎么说!id(43)|
耳朵的英文怎么说!id(44);

