/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zccl_ruiqianqi_tools_jni_NdkTools */

#ifndef _Included_com_zccl_ruiqianqi_tools_jni_NdkTools
#define _Included_com_zccl_ruiqianqi_tools_jni_NdkTools
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zccl_ruiqianqi_tools_jni_NdkTools
 * Method:    bridgeInit
 * Signature: (Lcom/zccl/ruiqianqi/tools/jni/NdkBridge;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_zccl_ruiqianqi_tools_jni_NdkTools_bridgeInit
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     com_zccl_ruiqianqi_tools_jni_NdkTools
 * Method:    getABI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zccl_ruiqianqi_tools_jni_NdkTools_getABI
  (JNIEnv *, jclass);

/*
 * Class:     com_zccl_ruiqianqi_tools_jni_NdkTools
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zccl_ruiqianqi_tools_jni_NdkTools_print
  (JNIEnv *, jclass);

/*
 * Class:     com_zccl_ruiqianqi_tools_jni_NdkTools
 * Method:    reset5Mic
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_zccl_ruiqianqi_tools_jni_NdkTools_reset5Mic
  (JNIEnv *, jclass);

/*
 * Class:     com_zccl_ruiqianqi_tools_jni_NdkTools
 * Method:    HdmiPowerOFF
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_zccl_ruiqianqi_tools_jni_NdkTools_HdmiPowerOFF
  (JNIEnv *, jclass);

/*
 * Class:     com_zccl_ruiqianqi_tools_jni_NdkTools
 * Method:    HdmiPowerON
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_zccl_ruiqianqi_tools_jni_NdkTools_HdmiPowerON
  (JNIEnv *, jclass);

/*
 * Class:     com_zccl_ruiqianqi_tools_jni_NdkTools
 * Method:    HdmiSwitchInternal
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_zccl_ruiqianqi_tools_jni_NdkTools_HdmiSwitchInternal
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_zccl_ruiqianqi_tools_jni_NdkTools
 * Method:    HdmiSwitchExternal
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_zccl_ruiqianqi_tools_jni_NdkTools_HdmiSwitchExternal
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_zccl_ruiqianqi_tools_jni_NdkTools
 * Method:    HdmiDppPowerON
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_zccl_ruiqianqi_tools_jni_NdkTools_HdmiDppPowerON
  (JNIEnv *, jclass);

/*
 * Class:     com_zccl_ruiqianqi_tools_jni_NdkTools
 * Method:    HdmiDppPowerOFF
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_zccl_ruiqianqi_tools_jni_NdkTools_HdmiDppPowerOFF
  (JNIEnv *, jclass);

/*
 * Class:     com_zccl_ruiqianqi_tools_jni_NdkTools
 * Method:    HdmiDppPowerRate
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_zccl_ruiqianqi_tools_jni_NdkTools_HdmiDppPowerRate
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_zccl_ruiqianqi_tools_jni_NdkTools
 * Method:    HdmiDppConfig
 * Signature: (IIIIII)I
 */
JNIEXPORT jint JNICALL Java_com_zccl_ruiqianqi_tools_jni_NdkTools_HdmiDppConfig
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_zccl_ruiqianqi_tools_jni_NdkTools
 * Method:    StmPinCtl
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_zccl_ruiqianqi_tools_jni_NdkTools_StmPinCtl
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_zccl_ruiqianqi_tools_jni_NdkTools
 * Method:    SystemBootUp
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_zccl_ruiqianqi_tools_jni_NdkTools_SystemBootUp
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_zccl_ruiqianqi_tools_jni_NdkTools
 * Method:    HdmiDppPowerStatus
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_zccl_ruiqianqi_tools_jni_NdkTools_HdmiDppPowerStatus
  (JNIEnv *, jclass);

/*
 * Class:     com_zccl_ruiqianqi_tools_jni_NdkTools
 * Method:    ProjectionStatus
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_zccl_ruiqianqi_tools_jni_NdkTools_ProjectionStatus
  (JNIEnv *, jclass);

/*
 * Class:     com_zccl_ruiqianqi_tools_jni_NdkTools
 * Method:    CheckAcCharger
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_zccl_ruiqianqi_tools_jni_NdkTools_CheckAcCharger
  (JNIEnv *, jclass);

/*
 * Class:     com_zccl_ruiqianqi_tools_jni_NdkTools
 * Method:    GsensorDataSwitch
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_zccl_ruiqianqi_tools_jni_NdkTools_GsensorDataSwitch
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_zccl_ruiqianqi_tools_jni_NdkTools
 * Method:    GetGsensorData
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_com_zccl_ruiqianqi_tools_jni_NdkTools_GetGsensorData
  (JNIEnv *, jclass, jintArray);

#ifdef __cplusplus
}
#endif
#endif
